### PR TITLE
Fix SequenceIDs warning when counter naturally overflows

### PR DESCRIPTION
**Pull request by mvicenzi**
### Description

This PR fixes the appearance of the following errors when the `eventCounter` of the CAEN board naturally overflows. This happens simultaneously for all East/West boards roughly every 40 hours (given our rate of trigger primitives). Example of the errors:

```
%MSG-d CAENV1730Readout:  InRunMap::Running 03-Apr-2023 11:46:55 CDT  Sequence ID 110458 CAENV1730Readout_generator.cc:1707
(FragID=8192)Missing triggers; previous trigger sequenceID / gap  = 16777215 / 4278190081, freeBlockCount=3080, activeBlockCount=0, fullyDrainedCount=0
%MSG
%MSG-d CAENV1730Readout:  InRunMap::Running 03-Apr-2023 11:46:55 CDT  Sequence ID 110458 CAENV1730Readout_generator.cc:2065
Missing data; previous fragment sequenceID / gap  = 16777215 / 4278190081
%MSG
%MSG-e CAENV1730Readout:  InRunMap::Running 03-Apr-2023 11:46:55 CDT  Sequence ID 110458 CAENV1730Readout_generator.cc:2073
SequnceIDs processed out of order!! 0 < 16777215
%MSG
```

- `eventCounter` is an unsigned 24-bit integer, so its max value is `16777215`. Then it goes back to `0` and an error (`SequnceIDs processed out of order!! 0 < 16777215`) is sent out. Despite being harmless because data and timestamps are correct, this has recently caused confusion and led to a precautionary run stop (run 9725) for fear of bad data being taken.
I think what I added should avoid this happening, but it may not be a very elegant solution... so suggestions are welcome!

- In addition, `auto readoutwindow_event_counter_gap= readoutwindow_event_counter - last_sent_rwcounter` [here](https://github.com/SBNSoftware/sbndaq-artdaq/blob/9cfde9f1b6534704d3e0b0bf8aa3ee4433615032/sbndaq-artdaq/Generators/Common/CAENV1730Readout_generator.cc#L1760) should also be a 24-bit unsigned int, but in the trace printout we get  `4278190081` so something is being treated as a uint_32: any suggestions on how to sanitize this?

Asking reviews (and ideas for the second issue) to PMT-related people: @wesketchum @gvittis @PetrilloAtWork 

### Testing details
- Still needs testing: however, given the current rate of trigger primitives, it requires >40 hours of consecutive data taking so I'm not sure how we can plan such a test.

### UPDATE:
- It was suggested to further sanitize the situation in order to avoid the same sequence ID to be used by multiple fragments in the same run. This was happening because the `readoutwindow_event_counter` was directly used as sequence ID of the corresponding fragment.
- Additional details on how this PR tries to overcome this are given [HERE](https://github.com/SBNSoftware/sbndaq-artdaq/pull/98#issuecomment-1513776317)

### CODE REVIEW

**Review by gvittis — APPROVED** [review]

**Review by PetrilloAtWork — APPROVED** [review]
Good enough!

Dealing with the nanosecond count of a timestamp has similarities with this problem, when it happens that you need to compare `999'984'787` and `000'005'213`.
In these cases, I usually go with something like `if (ns2 < ns1) ns2 += 1'000'000'000;`. This assumes that `ns2` must be larger than `ns1`. Unfortunately this approach does not fit this case well, since the order also needs to be questioned.

**Comment by aaduszki** [comment]
@mvicenzi could you please confirm the following: the fix prevents the warning message from appearing, but it still allows for two fragments within the same run to have the same sequenceID?
@gennadiy-fnal could it cause any issues?

**Comment by mvicenzi** [comment]
> @mvicenzi could you please confirm the following: the fix prevents the warning message from appearing, but it still allows for two fragments within the same run to have the same sequenceID?

Yes. That's correct. The counter overflows, so there will be two (or more) fragments with the same `setSequenceID` in the run. Since they are very far apart in time, I suppose this should have no impact downstream but I'm not familiar with how this information is being used down the line.

**Comment by aaduszki** [comment]
@mvicenzi we discussed on the Online Meeting, and it was suggested that it's better to play it safe, and to avoid repeating the sequence ID within a run. Do you think you could implement some solution, e.g., by introducing a variable which keeps track of how many times the counter overflown, and then adding n·2²⁴ to the sequence ID?

**Comment by mvicenzi** [comment]
@aaduszki Yes, I think it should be fairly simple to disentagle the sequence ID of the fragment from the event counter in the fragment header. I will work on this asap and update this PR.

**Comment by mvicenzi** [comment]
Following the above suggestions, I have done the following:

- There is now a new variable `readoutwindow_sequence_id`, which is used to set the fragment sequence id. It is a `uint64_t` and keeps track of the number of overflows. This should avoid repeating sequenceIDs in the same run:
```uint64_t readoutwindow_sequence_id = uint64_t{readoutwindow_event_counter + fOverflowCounter*(max_rwcounter+1u)};```

- It is important to note that  `readoutwindow_event_counter` is still internally used as key of `fTimestampMap` to retrieve timestamps when packaging fragments. It can overflow (with no error mistakenly printed), but this is okay as the timestamp in the map is overwritten a long time after the previous value was used. See [here](https://github.com/SBNSoftware/sbndaq-artdaq/blob/27aace3fb3f229d1730adc2905152090903c7be0/sbndaq-artdaq/Generators/Common/CAENV1730Readout_generator.cc#L1524).
``` fTimestampMap[uint32_t{header->eventCounter}] = fTS; ```

- I removed an unused fcl parameter which did nothing (as discussed in the past with @gvittis).

As the code is quite intricate, I might have misunderstood some of the logic behind it so these changes should really go through some testing... Also, it would be good to get @wesketchum's review on them.

**Comment by gennadiy-fnal** [comment]
We have received two positive reviews, which means I will proceed with merging this code. However, we still need to verify the validity of the data it produces.

**Pull request merged**
