### PR TITLE
Add configurable network group and logging of firmware error words.

### PR DESCRIPTION
**Pull request by jsensenig**
There are 2 changes,
* Make the network group a configurable parameter.
* Decode and print error words from the firmware to log file.

### CODE REVIEW

**Comment by wbadgett** [comment]
I recommend taking the FCL parameter of the PTB server's DAQ address directly from the FCL file without any modification(s)    This should make running at D0 and ND more robust in general

**Review by wbadgett — CHANGES_REQUESTED** [review]
Take the FCL network name of the PTB server's DAQ device literally with no changes

**Review by wbadgett — APPROVED** [review]

**Comment by wbadgett** [comment]
Jon, please post a run number and location (ND or D0) for your code test(s)

**Comment by jsensenig** [comment]
This code was tested successfully,
* Location: ND
* Run: 1393
* Components: tpc01, tpc02, ptb01

**Review by kalradaisy — APPROVED** [review]

**Comment by jsensenig** [comment]
@gennadiy-fnal this PR along with an associated one in `sbndaq` has been reviewed by Bill and Daisy so I would like to request it to be merged into the develop branch. Thank you!

**Pull request merged**
