### PR TITLE
Remove generated_fragments_per_event

### PR DESCRIPTION
**Pull request by aaduszki**
### Description

`generated_fragments_per_event` fhicl parameter is deprecated since sbndaq v1_08_05. While it doesn't cause harm, it produces warnings, which can be misleading. However the parameter is read by sbndaq code, and cannot be simply removed.
It appears to me that all occurrences in sbndaq code do nothing, and can be safely removed, which is done in this PR.

### Related Repository Branches

sbndaq v1_08_05 and artdaq version it uses
https://github.com/art-daq/artdaq/pull/213

### Testing details
- Not tested yet!!! It must be tested with a configuration with `generated_fragments_per_event` parameter removed
- *Run number associated with test*: ///update information after the test is done///

### CODE REVIEW

**Review by jzettle — APPROVED** [review]
The changes look harmless to me I presume this is tested already? It does remove the ability to stop sending fragments from things like the trigger and still look at metrics and keep event accounting. Maybe we do not want this anymore not that the systems are stable but pointing out that effect of these changes.

**Comment by jzettle** [comment]
Of course I read quickly and missed the "not tested yet" point.

**Review by dtorretta56 — APPROVED** [review]
It seems pretty straightforward. needs testing.

**Comment by aaduszki** [comment]
> The changes look harmless to me I presume this is tested already? It does remove the ability to stop sending fragments from things like the trigger and still look at metrics and keep event accounting. Maybe we do not want this anymore not that the systems are stable but pointing out that effect of these changes.

No, I just quickly wrote (or rather deleted) the code, we should schedule a test next week

**Review by jzettle — APPROVED** [review]
I still think the changes here look harmless to me from the previous review on this.

**Review by gennadiy-fnal — APPROVED** [review]
I find changes pertaining to the removal of the generated_fragments_per_event parameters to be reasonable. Further testing will be conducted as a part of the integration test at the Icarus cluster. The code builds OK, so it's safe to proceed with merging code into the release branch.

**Pull request merged**
