### PR TITLE
Feature/rh bottom crt

### PR DESCRIPTION
**Pull request by rhowell42**
### Description

Adding fragment generator for the bottom CRT. Adding backend C++/C code integrated into the fragment generator to communicate with the bottom CRT hardware. Moslty complete, need to finalize fragment timestamp calculation.

### Related Repository Branches

feature/rh_bottomCRT in sbndaq
feature/rh_bottomCRT in sbndaq-artdaq-core

### Testing details
NOT FULLY TESTED YET. FOR GENNADIY TO LOOK OVER.

### CODE REVIEW

**Comment by ron003** [comment]
There are many .png files added. Question: do all the .png files need to be added?

**Comment by rhowell42** [comment]
No they don't, that whole directory path is vestigial and is only used by bottom CRT people for calibration purposes. I thought I removed it from this feature branch but apparently not

**Comment by rhowell42** [comment]
Sorry Ron, I meant the whole ICARUS_DAQ directory is unnecessary for the PR. I can remove and cleanup this afternoon

**Comment by ron003** [comment]
OK, thanks

**Pull request closed without merging**
