### PR TITLE
Feature/jcrespo caenv1740 b

### PR DESCRIPTION
**Pull request by jicrespo**
### Description

Add BoardReader for the CAEN V1740 modules via the A3818C PCIe controller to read out the X-ARAPUCAs. Based on the BoardReader for the CAEN V1730 modules for the PMT system.

### Related Repository Branches

https://github.com/SBNSoftware/sbndaq-artdaq-core/tree/feature/jcrespo_CAENV1740B
https://github.com/SBNSoftware/sbndaq/tree/feature/jcrespo_CAENV1740B

### Testing details

Tested at SBN-ND:
- Run 17413: Dummy V1730 pushing with PTB Event Triggers + two V1740 in pull-mode with PTB Flash Triggers.
- Run with full DAQ to be added.

### CODE REVIEW

**Comment by afilkins** [comment]
Things ran well, but there were a lot of info level messages for every event. Could we turn it down to a lower level or add a verbosity fcl parameter? 

```
Info / CAENV1740Readout
07-Nov-2024 18:46:31 CST
sbnd-pds04.fnal.gov (131.225.250.156)
UDPMessage 0 / PID 25517 / CAENV1740Readout_generator.cc:1638
boardreader / Early / pre-events
(FragID=41232): XA_EVENT_COUNTER=6336, XA_EVENT_SIZE=18436, XA_TIME_TAG=40949628

Info / CAENV1740Readout
07-Nov-2024 18:46:31 CST
sbnd-pds04.fnal.gov (131.225.250.156)
UDPMessage 0 / PID 25517 / CAENV1740Readout_generator.cc:1932
boardreader / Early / pre-events
Created fragment 41232 sequenceID 6336 for event 6336 triggerTimeTag 40949628 ts=1731026791327597024
```

**Comment by afilkins** [comment]
This also is really just for SBND's 1740s and could be moved out of the Common directory

**Review by afilkins — CHANGES_REQUESTED** [review]
Can we move this to the SBND directory?

**Comment by jicrespo** [comment]
> Can we move this to the SBND directory?

Done. Requires to run `mrb zd` after the change.

**Comment by jicrespo** [comment]
> Things ran well, but there were a lot of info level messages for every event. Could we turn it down to a lower level or add a verbosity fcl parameter?

Done. Reverted to the original TRACE level.

**Review by afilkins — APPROVED** [review]
thanks looks good! Runs well

**Pull request merged**
