### PR TITLE
Feature/aa metric levels

### PR DESCRIPTION
**Pull request by aaduszki**
### Description

Changed metric levels in ICARUS and Common code to 11–12, following discussion on the ICARUS online meeting.
Opening draft pull to start code review and discussion.
I'm asking subdetector DAQ experts to review changes to their boardreaders.
I guess SBND would like to follow with similar changes to their code. We may need a discussion about it.

### Related Repository Branches

--

### Testing details

*Testing needed! Tests not done yet!*

_(Note: edit as appropriate.)_
- *Where it was tested*: (e.g. SBN-FD, SBN-ND, DAB, etc.)
- *Run number associated with test*: 
- Other information:

### CODE REVIEW

**Comment by dtorretta56** [comment]
The changes to the WhiteRabbitReadout_generator.cc look fine to me. I approve.

**Comment by gennadiy-fnal** [comment]
Code changes appear to be reasonable.

**Review by gennadiy-fnal — APPROVED** [review]

**Review by mvicenzi — APPROVED** [review]
Approving from the PMT side.

**Review by hausnerh — APPROVED** [review]
The changes to the PhysCrate generators seem perfectly fine to me

**Review by jzettle — APPROVED** [review]
I have no problem with the changes

**Review by henrylay97 — APPROVED** [review]
Following yesterday's SBND DAQ meeting I now understand this better. The changes to the BernCRT elements are fine from an SBND side :)

**Review by matthewmurphy15 — APPROVED** [review]
Changes look fine for bottom CRT

**Pull request merged**
